# disable some cops that are too opinionated
# and make code less readable
Style/NumericPredicate:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Style/EachWithObject:
  Enabled: false

Style/EmptyCaseCondition:
  Enabled: false
