Style/NumericPredicate:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

# omg ruby you really prefer magic over being clear and explicit
Style/EachWithObject:
  Enabled: false
